[package]
name = "basic_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [lib]
# proc-macro = true

[dependencies]
num = "0.4.0"
quote = "1.0.8"
syn = {version="1.0.57",features=["full","fold"]}
